"""
Full Code Generation from Natural Language
Build complete applications from descriptions
"""
from typing import Dict, List, Optional
from pathlib import Path
import json

class ProjectGenerator:
    def __init__(self):
        self.templates = {
            'react': {
                'files': ['package.json', 'src/App.js', 'src/index.js', 'README.md'],
                'structure': ['src', 'public', 'tests']
            },
            'python': {
                'files': ['main.py', 'requirements.txt', 'README.md', 'tests/test_main.py'],
                'structure': ['src', 'tests', 'docs']
            },
            'nodejs': {
                'files': ['index.js', 'package.json', 'README.md', '.env.example'],
                'structure': ['src', 'tests', 'config']
            }
        }
    
    def generate_project(self, description: str, tech_stack: str = 'python') -> Dict[str, str]:
        files = {}
        
        if tech_stack == 'python':
            files['main.py'] = self._generate_python_app(description)
            files['requirements.txt'] = self._generate_requirements(description)
            files['README.md'] = self._generate_readme(description, tech_stack)
            files['tests/test_main.py'] = self._generate_tests(description, tech_stack)
        
        elif tech_stack == 'react':
            files['src/App.js'] = self._generate_react_app(description)
            files['package.json'] = self._generate_package_json(description)
            files['README.md'] = self._generate_readme(description, tech_stack)
        
        elif tech_stack == 'nodejs':
            files['index.js'] = self._generate_nodejs_app(description)
            files['package.json'] = self._generate_package_json(description)
            files['README.md'] = self._generate_readme(description, tech_stack)
        
        return files
    
    def _generate_python_app(self, description: str) -> str:
        return f'''"""
{description}
Auto-generated by Aether AI
"""

def main():
    print("Application: {description}")
    # TODO: Implement core logic
    
if __name__ == "__main__":
    main()
'''
    
    def _generate_react_app(self, description: str) -> str:
        return f'''import React from 'react';

// {description}
// Auto-generated by Aether AI

function App() {{
  return (
    <div className="App">
      <h1>{description}</h1>
      <p>Your app is ready!</p>
    </div>
  );
}}

export default App;
'''
    
    def _generate_nodejs_app(self, description: str) -> str:
        return f'''// {description}
// Auto-generated by Aether AI

const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.get('/', (req, res) => {{
  res.send('{description} - Server running!');
}});

app.listen(PORT, () => {{
  console.log(`Server running on port ${{PORT}}`);
}});
'''
    
    def _generate_requirements(self, description: str) -> str:
        return '''flask>=2.0.0
requests>=2.28.0
python-dotenv>=0.19.0
'''
    
    def _generate_package_json(self, description: str) -> str:
        return json.dumps({
            "name": description.lower().replace(' ', '-'),
            "version": "1.0.0",
            "description": description,
            "main": "index.js",
            "scripts": {
                "start": "node index.js",
                "test": "echo \"No tests yet\""
            },
            "dependencies": {}
        }, indent=2)
    
    def _generate_readme(self, description: str, tech: str) -> str:
        return f'''# {description}

Auto-generated by **Aether AI**

## Description
{description}

## Tech Stack
- **{tech.upper()}**

## Installation
```bash
# Install dependencies
{"pip install -r requirements.txt" if tech == "python" else "npm install"}
```

## Usage
```bash
# Run the application
{"python main.py" if tech == "python" else "npm start"}
```

## Generated by
Aether AI - JARVIS-Level Assistant
'''
    
    def _generate_tests(self, description: str, tech: str) -> str:
        if tech == 'python':
            return f'''import unittest
from main import main

class TestApp(unittest.TestCase):
    def test_main(self):
        # TODO: Add tests
        pass

if __name__ == '__main__':
    unittest.main()
'''
        return ''

class CodeRefactorer:
    def refactor(self, code: str, style: str = 'clean') -> str:
        lines = code.split('\n')
        refactored = []
        
        for line in lines:
            line = line.rstrip()
            if style == 'clean':
                if line and not line.startswith('#'):
                    refactored.append(line)
        
        return '\n'.join(refactored)

project_generator = ProjectGenerator()

def generate_app(description: str, tech_stack: str = 'python') -> Dict[str, str]:
    return project_generator.generate_project(description, tech_stack)

def create_project_files(description: str, tech_stack: str, output_dir: Path):
    files = generate_app(description, tech_stack)
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    for file_path, content in files.items():
        full_path = output_dir / file_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(content)
    
    return len(files)
